services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa-server
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies/policy.rego"
      - "/policies/policy.json"
    ports:
      - "8181:8181"
    volumes:
      - ./config:/policies:ro
    networks:
      - policy-mcp-net

networks:
  policy-mcp-net:
    external: true